
creation_rules:
  - path_regex: flux/secrets/.*\.sops\.yaml$
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - age1pjn3ewajpyer3q20yvh200x4f55t7x57sewvvmc043tgfd8h0ahqau8ws4
